# Stage 1: Build the Vite app
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Construimos pasando la variable de entorno para que el build sepa que usa /api
RUN VITE_API_URL=/ npm run build

# Stage 2: Serve the app with Nginx
FROM nginx:alpine
# Copiamos la configuración de Nginx (Reverse Proxy)
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copiamos los archivos estáticos generados por Vite
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
