[DEFAULT]
# List of migration source directories.
sources = migrations
# Database connection URI.
# En la máquina local el servicio de postgresql (Docker) se expone en localhost:5432
database = postgresql://myuser:superseguro123@localhost:5432/mydb
batch_mode = off
verbosity = 0
